name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://www.trashcan.icu/img/leetcode-status-dark.svg > ./status.svg
      - name: Commit to the repo
        run: |
          git config --global user.name "wsmbsbbz/github-actions-demo"
          git config --global user.email "1037214973@qq.com"
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m '🎉 Update Generated Files' || echo
          git push

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "zh_CN"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
